name: React App Deployment

on:
    push:
        branches: main

jobs:
    react-app-deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v2
            - name: Use Node.js 18.x
              uses: actions/setup-node@v1
              with:
                node-version: 18.x
            - name: Install dependencies
              uses: npm install
            - name: Test
              uses: npm test
            - name: Generate build
              uses: npm build
            - name: Generate artifact
              uses: actions/upload-artifact@v1
              with: 
                name: react-app-deployment
                path: build
