name: React App Deployment
on:
    push:
        branches: main
jobs:
    react-app-deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v4
            - name: Use Node.js 12.x
              uses: actions/setup-node@v4
              with:
                node-version: 12.x
                cache: npm
            - name: Install dependencies
              uses: npm install
            - name: Test
              uses: npm test
            - name: Generate build
              uses: npm build
            - name: Generate artifact
              uses: actions/upload-artifact@v4
              with:
                name: react-app-deployment
                path: build
